# Non Graded Challenge 5

- Nama: Gihon Christy
- Program: FTDS batch 14

Saya akan mengerjakan Non-graded challenge yang diambil dari sumber: https://github.com/ardhiraka/FSDS_Guidelines/blob/master/p0/w2/assignments/NG5.md

In [2]:
# Mengimport semua libraries yang akan digunakan
import numpy as np

**1. Membuat tensor dengan Python (Vektor lih. sumber)**

In [8]:
# Memasukan semua Matrix ke dalam python terlebih dahulu
M = np.array([[23, 50],
             [7, 12]])
N = np.array([[57, 67],
              [99, 43]])
O = np.array([[75, 21],
             [57, 12]])
P = np.array([[87, 26],
             [18, 84]])
print(M,N)
print(O,P)

[[23 50]
 [ 7 12]] [[57 67]
 [99 43]]
[[75 21]
 [57 12]] [[87 26]
 [18 84]]


In [21]:
Tensor = np.array([M,N,O,P])
Tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 43]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

In [22]:
print(Tensor.shape)
print(Tensor)

(4, 2, 2)
[[[23 50]
  [ 7 12]]

 [[57 67]
  [99 43]]

 [[75 21]
  [57 12]]

 [[87 26]
  [18 84]]]


**2. Perkalian Matrix**

In [24]:
a1 = np.array([[23, 50, 19],
               [7, 12, 109],
               [57, 67, 98]])
a2 = np.array([17, 22, 19])

print(a1,a2)
print(a1.shape)
print(a2.shape)

# Jumlah kolom matrix a1 = jumlah baris matrix a2, sehingga dapat dikalikan dengan metode perkalian matrix aljabar linear

[[ 23  50  19]
 [  7  12 109]
 [ 57  67  98]] [17 22 19]
(3, 3)
(3,)


In [25]:
# perkalian matrix
a1.dot(a2)

array([1852, 2454, 4305])

In [27]:
# Hasil perkalian jika dikalikan dengan metode hadamart product
a1*a2

array([[ 391, 1100,  361],
       [ 119,  264, 2071],
       [ 969, 1474, 1862]])

**3. transpose, Inverse, dan Determinan**

In [28]:
# Matrix dalam soal = a1
a1

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [30]:
L = a1
L

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [31]:
# Transpose
L.T

array([[ 23,   7,  57],
       [ 50,  12,  67],
       [ 19, 109,  98]])

In [32]:
# Inverse
L_inv = np.linalg.inv(L)
L_inv

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])

In [33]:
# Pengecekan L_inv = invers dari matrix L, jika benar maka L * L inverse = matrix identitas
L @ L_inv

array([[1.00000000e+00, 1.90819582e-17, 1.32923186e-16],
       [7.22078647e-17, 1.00000000e+00, 5.44269491e-17],
       [6.73506390e-16, 1.97758476e-16, 1.00000000e+00]])

In [34]:
np.round(L@L_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
# Determinant
np.linalg.det(L)

131344.0000000002